HUD_FRAME_COUNT      = 6
HUD_FRAME_THRESHOLDS = (80, 60, 40, 20, 0)
EDGE_MARGIN          = 20
GROUP_GAP            = 10
LABEL_FONT_SIZE      = 16
LABEL_GAP            = 12

AMMO_ICON_HEIGHT        = 56
AMMO_BAR_WIDTH          = 150
AMMO_BAR_HEIGHT         = 11
AMMO_BAR_BASELINE_NUDGE = 4

HEALTH_ICON_HEIGHT        = 46
HEALTH_ICON_GAP           = GROUP_GAP
HEALTH_BAR_WIDTH          = AMMO_BAR_WIDTH
HEALTH_BAR_HEIGHT         = AMMO_BAR_HEIGHT
HEALTH_BAR_BASELINE_NUDGE = AMMO_BAR_BASELINE_NUDGE
HEALTH_LABEL_GAP          = 8

TANK_TRACK_COLOR  = (14, 27, 38)
TANK_BORDER_COLOR = (8, 18, 27)
TANK_FILL_COLOR   = (60, 160, 224)
TANK_LABEL_COLOR  = (191, 224, 244)

HEALTH_TRACK_COLOR  = (26, 22, 20)
HEALTH_BORDER_COLOR = (12, 10, 9)
HEALTH_FILL_COLOR   = (226, 59, 78)
HEALTH_LABEL_COLOR  = (240, 201, 205)

VALUE_COLOR = (255, 255, 255)

CROSSHAIR_HEIGHT = 22
CROSSHAIR_SPIN_SPEED    = 720
CROSSHAIR_SPIN_RESPONSE = 9
CROSSHAIR_REST_SNAP     = 12

POINTER_HEIGHT     = 44
POINTER_HOTSPOT_X  = 0.0
POINTER_HOTSPOT_Y  = 0.0

ICON_COLUMN_WIDTH = 40

KILL_ICON_HEIGHT         = 56
KILL_GROUP_GAP           = 18
KILL_COUNT_FONT_SIZE     = 24
KILLS_LABEL_FONT_SIZE    = LABEL_FONT_SIZE
KILL_ICON_TEXT_GAP       = GROUP_GAP
KILLS_LABEL_GAP          = 8
KILL_COUNT_BASELINE_DROP = 9
KILL_SHADOW_OFFSET       = 2

KILL_COUNT_COLOR  = (255, 255, 255)
KILL_COUNT_SHADOW = (15, 42, 8)
KILLS_LABEL_COLOR = (191, 230, 168)