ZOMBIE_SPRITE_SCALE       = 0.1
ZOMBIE_SPEED              = 3.0
ZOMBIE_HITS_TO_DIE        = 4
ZOMBIE_SECONDS_PER_FRAME  = 0.23
COLLISION_RADIUS_FRACTION = 0.3
SPAWN_INTERVAL_SECONDS    = 3.0
MAX_ZOMBIES               = 10